materials/arcjail/winner.vmt
materials/arcjail/winner.vtf
materials/arcjail/loser.vmt
materials/arcjail/loser.vtf
overlays/arcjail/3.vmt
overlays/arcjail/3.vtf
overlays/arcjail/2.vmt
overlays/arcjail/2.vtf
overlays/arcjail/1.vmt
overlays/arcjail/1.vtf
overlays/arcjail/flawless.vmt
overlays/arcjail/flawless.vtf