materials/arcjail/winner.vmt
materials/arcjail/winner.vtf
materials/arcjail/loser.vmt
materials/arcjail/loser.vtf
materials/overlays/arcjail/3.vmt
materials/overlays/arcjail/3.vtf
materials/overlays/arcjail/2.vmt
materials/overlays/arcjail/2.vtf
materials/overlays/arcjail/1.vmt
materials/overlays/arcjail/1.vtf
materials/overlays/arcjail/flawless.vmt
materials/overlays/arcjail/flawless.vtf