materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_d1.vmt
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_d1.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_d2.vmt
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_d2.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_d4.vmt
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_d4.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_exponent.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristlowerbody_n.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_d1.vmt
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_d1.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_d2.vmt
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_d2.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_d4.vmt
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_d4.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_exponent.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_n.vtf
materials/models/player/arcjail/csgo/regular/balkanterroristupperbody_selfillummask.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_varianta.vmt
materials/models/player/arcjail/csgo/regular/tm_balkan_head_varianta.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_varianta_exponent.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_varianta_normal.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantb.vmt
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantb.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantb_exponent.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantb_normal.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantc.vmt
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantc.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantc_exponent.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantc_normal.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantd.vmt
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantd.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantd_exponent.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variantd_normal.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variante.vmt
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variante.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variante_exponent.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_head_variante_normal.vtf
materials/models/player/arcjail/csgo/regular/tm_balkan_shared.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_d1.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_d1.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_d2.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_d2.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_d4.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_d4.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_exponent.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristlowerbody_n.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_d1.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_d1.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_d2.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_d2.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_d4.vmt
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_d4.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_exponent.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_n.vtf
materials/models/player/arcjail/csgo/rebel/balkanterroristupperbody_selfillummask.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_varianta.vmt
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_varianta.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_varianta_exponent.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_varianta_normal.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantb.vmt
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantb.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantb_exponent.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantb_normal.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantc.vmt
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantc.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantc_exponent.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantc_normal.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantd.vmt
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantd.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantd_exponent.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variantd_normal.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variante.vmt
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variante.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variante_exponent.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_head_variante_normal.vtf
materials/models/player/arcjail/csgo/rebel/tm_balkan_shared.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_d1.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_d1.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_d2.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_d2.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_d4.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_d4.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_exponent.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristlowerbody_n.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_d1.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_d1.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_d2.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_d2.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_d4.vmt
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_d4.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_exponent.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_n.vtf
materials/models/player/arcjail/csgo/delta/balkanterroristupperbody_selfillummask.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_varianta.vmt
materials/models/player/arcjail/csgo/delta/tm_balkan_head_varianta.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_varianta_exponent.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_varianta_normal.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantb.vmt
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantb.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantb_exponent.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantb_normal.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantc.vmt
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantc.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantc_exponent.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantc_normal.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantd.vmt
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantd.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantd_exponent.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variantd_normal.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variante.vmt
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variante.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variante_exponent.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_head_variante_normal.vtf
materials/models/player/arcjail/csgo/delta/tm_balkan_shared.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_d1.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_d1.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_d2.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_d2.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_d4.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_d4.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_exponent.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristlowerbody_n.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_d1.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_d1.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_d2.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_d2.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_d4.vmt
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_d4.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_exponent.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_n.vtf
materials/models/player/arcjail/csgo/charlie/balkanterroristupperbody_selfillummask.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_varianta.vmt
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_varianta.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_varianta_exponent.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_varianta_normal.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantb.vmt
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantb.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantb_exponent.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantb_normal.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantc.vmt
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantc.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantc_exponent.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantc_normal.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantd.vmt
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantd.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantd_exponent.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variantd_normal.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variante.vmt
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variante.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variante_exponent.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_head_variante_normal.vtf
materials/models/player/arcjail/csgo/charlie/tm_balkan_shared.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_d1.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_d1.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_d2.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_d2.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_d4.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_d4.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_exponent.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristlowerbody_n.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_d1.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_d1.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_d2.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_d2.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_d4.vmt
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_d4.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_exponent.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_n.vtf
materials/models/player/arcjail/csgo/bravo/balkanterroristupperbody_selfillummask.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_varianta.vmt
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_varianta.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_varianta_exponent.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_varianta_normal.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantb.vmt
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantb.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantb_exponent.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantb_normal.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantc.vmt
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantc.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantc_exponent.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantc_normal.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantd.vmt
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantd.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantd_exponent.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variantd_normal.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variante.vmt
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variante.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variante_exponent.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_head_variante_normal.vtf
materials/models/player/arcjail/csgo/bravo/tm_balkan_shared.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_d1.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_d1.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_d2.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_d2.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_d4.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_d4.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_exponent.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristlowerbody_n.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_d1.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_d1.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_d2.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_d2.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_d4.vmt
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_d4.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_exponent.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_n.vtf
materials/models/player/arcjail/csgo/alpha/balkanterroristupperbody_selfillummask.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_varianta.vmt
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_varianta.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_varianta_exponent.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_varianta_normal.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantb.vmt
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantb.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantb_exponent.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantb_normal.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantc.vmt
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantc.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantc_exponent.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantc_normal.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantd.vmt
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantd.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantd_exponent.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variantd_normal.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variante.vmt
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variante.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variante_exponent.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_head_variante_normal.vtf
materials/models/player/arcjail/csgo/alpha/tm_balkan_shared.vmt
models/player/arcjail/csgo/alphab.dx90.vtx
models/player/arcjail/csgo/alphab.mdl
models/player/arcjail/csgo/alphab.phy
models/player/arcjail/csgo/alphab.vvd
models/player/arcjail/csgo/alphad.dx90.vtx
models/player/arcjail/csgo/alphad.mdl
models/player/arcjail/csgo/alphad.phy
models/player/arcjail/csgo/alphad.vvd
models/player/arcjail/csgo/alphae.dx90.vtx
models/player/arcjail/csgo/alphae.mdl
models/player/arcjail/csgo/alphae.phy
models/player/arcjail/csgo/alphae.vvd
models/player/arcjail/csgo/bravob.dx90.vtx
models/player/arcjail/csgo/bravob.mdl
models/player/arcjail/csgo/bravob.phy
models/player/arcjail/csgo/bravob.vvd
models/player/arcjail/csgo/bravod.dx90.vtx
models/player/arcjail/csgo/bravod.mdl
models/player/arcjail/csgo/bravod.phy
models/player/arcjail/csgo/bravod.vvd
models/player/arcjail/csgo/bravoe.dx90.vtx
models/player/arcjail/csgo/bravoe.mdl
models/player/arcjail/csgo/bravoe.phy
models/player/arcjail/csgo/bravoe.vvd
models/player/arcjail/csgo/charlieb.dx90.vtx
models/player/arcjail/csgo/charlieb.mdl
models/player/arcjail/csgo/charlieb.phy
models/player/arcjail/csgo/charlieb.vvd
models/player/arcjail/csgo/charlied.dx90.vtx
models/player/arcjail/csgo/charlied.mdl
models/player/arcjail/csgo/charlied.phy
models/player/arcjail/csgo/charlied.vvd
models/player/arcjail/csgo/charliee.dx90.vtx
models/player/arcjail/csgo/charliee.mdl
models/player/arcjail/csgo/charliee.phy
models/player/arcjail/csgo/charliee.vvd
models/player/arcjail/csgo/deltab.dx90.vtx
models/player/arcjail/csgo/deltab.mdl
models/player/arcjail/csgo/deltab.phy
models/player/arcjail/csgo/deltab.vvd
models/player/arcjail/csgo/deltad.dx90.vtx
models/player/arcjail/csgo/deltad.mdl
models/player/arcjail/csgo/deltad.phy
models/player/arcjail/csgo/deltad.vvd
models/player/arcjail/csgo/deltae.dx90.vtx
models/player/arcjail/csgo/deltae.mdl
models/player/arcjail/csgo/deltae.phy
models/player/arcjail/csgo/deltae.vvd
models/player/arcjail/csgo/rebelb.dx90.vtx
models/player/arcjail/csgo/rebelb.mdl
models/player/arcjail/csgo/rebelb.phy
models/player/arcjail/csgo/rebelb.vvd
models/player/arcjail/csgo/rebeld.dx90.vtx
models/player/arcjail/csgo/rebeld.mdl
models/player/arcjail/csgo/rebeld.phy
models/player/arcjail/csgo/rebeld.vvd
models/player/arcjail/csgo/rebele.dx90.vtx
models/player/arcjail/csgo/rebele.mdl
models/player/arcjail/csgo/rebele.phy
models/player/arcjail/csgo/rebele.vvd
models/player/arcjail/csgo/regularb.dx90.vtx
models/player/arcjail/csgo/regularb.mdl
models/player/arcjail/csgo/regularb.phy
models/player/arcjail/csgo/regularb.vvd
models/player/arcjail/csgo/regulard.dx90.vtx
models/player/arcjail/csgo/regulard.mdl
models/player/arcjail/csgo/regulard.phy
models/player/arcjail/csgo/regulard.vvd
models/player/arcjail/csgo/regulare.dx90.vtx
models/player/arcjail/csgo/regulare.mdl
models/player/arcjail/csgo/regulare.phy
models/player/arcjail/csgo/regulare.vvd